# Generated by Django 3.0.3 on 2021-05-07 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploader', models.CharField(default='0xecho', max_length=120)),
                ('image', models.ImageField(upload_to='memes/%Y/%m/%d')),
                ('likes', models.IntegerField(default=0)),
            ],
        ),
    ]
